name: CI Mentoria

on:
  workflow_dispatch:

jobs:
  tests:
    # Configura√ß√£o do ambiente (SO, navegador, etc.)
    runs-on: ubuntu-latest

    # Vari√°veis de ambiente (URLs, portas, etc.)
    env:
      API_BASE_URL: http://localhost:3000
      PORT: 4808

    steps:
      # [projetos] (aplica√ß√µes, reposit√≥rios de teste, etc.)
      - name: Checkout do Reposit√≥rio
        uses: actions/checkout@v4

      # [depend√™ncias do projeto] (Node/npm, Java/maven, Python/pip, etc.)
      - name: Instalando as depend√™ncias
        run: npm install

      - name: Iniciar o servidor de mocks
        run: npm run mock-server &

      - name: Iniciar servidor da aplica√ß√£o
        run: npm run server &

      - name: Executar os testes (ignorar se n√£o houver)
        run: |
          if [ -f package.json ] && grep -q '"test"' package.json; then
            echo "üîç Execut